- name: Set registry fact if this is the registry host
  set_fact:
    registry: true
  when: docker_registry in ansible_all_ipv4_addresses

- name: Install packages
  apt: pkg={{ item }} state=present
  with_items:
    - docker-compose
    - git
    - tree

- name: Create cursus user
  user:
    name: cursus
    password: "$6$1IyW/79Y$7LbxJx8kST2g5Wv4A8Op9lOJO16TLuauu6TM17xp2iK1O1r7T9Kkmo0EnhPuY40vpaHh4ggeO7vwPIV0MyNo31"
    update_password: always
    shell: /bin/bash
    groups:
      - docker
      - sudo

#docker run -d -p 5000:5000 --restart always --name registry registry:2
- name: "Launch docker registry"
  docker_container:
    name: registry
    image: "registry:2"
    ports:
      - "{{docker_registry}}:5000:5000"
    restart_policy: unless-stopped
    state: started
  when: registry is defined

- name: "Add curusregistry to hostfile"
  lineinfile:
    path: "/etc/hosts"
    regexp: 'cursusregistry'
    line: '{{docker_registry}} cursusregistry'

- name: "Clone course repository"
  git:
    repo: 'https://github.com/bertbaron/dockercourse.git'
    dest: /home/cursus/opdrachten
    version: master
    force: no
  become: true
  become_user: cursus