#!/bin/bash
#
# Script to install stuff locally on course pc's
#
# To execute, run:
#
# wget -O localinstall https://raw.githubusercontent.com/bertbaron/dockercourse-setup/master/localinstall && bash ./localinstall

set -eu -o pipefail

cd "$HOME"

forceClean=false
while [[ $# -gt 0 ]]; do
    key="$1"
    case $key in
        -f|--force)
        forceClean=true
        shift
    esac
done

if [[ "$forceClean" = true ]]; then

  echo "Force clean install?"
  read -p "Are you sure? " -n 1 -r
  echo
  if [[ ! $REPLY =~ ^[Yy]$ ]]
  then
      exit
  fi

  echo "Cleaning..."

  docker swarm leave -f 2>&1 || true
  docker rm -f $(docker ps -aq) 2>&1 || true
  docker rmi -f $(docker images -aq) 2>&1 || true
  docker volume rm -f $(docker volume ls -q) 2>&1 || true
  docker system prune -f
  sudo rm -rf dockercourse
  pkill firefox || true
  rm -rf .mozilla/firefox
  echo "done cleanup"
fi

last_update=$(stat -c %Y /var/lib/apt/periodic/update-success-stamp)
now=$(date +%s)
if [ $((now - last_update)) -gt 3600 ]; then
  sudo apt-get update
fi

installDocker() {
    install apt-transport-https ca-certificates curl software-properties-common
    curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
    sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
    sudo apt-get update
}

install() {
	cmd="$1"
	package="$2"
	which "$cmd" > /dev/null || sudo apt-get install -y "$package"
}

# Setup docker and prerequisites
install curl curl
which docker > /dev/null || installDocker

install docker-compose docker-compose
install git git
install vim vim

addToDockerGroup() {
  sudo usermod -a -G docker $USER
  echo "User added to docker group, new login required"
  exit 1
}

groups | grep docker > /dev/null || addToDockerGroup

myIp='192.168.100.53'

if grep -q cursusregistry /etc/hosts; then
    sudo sed -i 's/^.*cursusregistry.*$/'$myIp' cursusregistry/g' /etc/hosts
else
    echo "$myIp cursusregistry" | sudo tee -a /etc/hosts > /dev/null
fi

# https://owncloud.fambaron.nl/s/k8qRoPkFn4XB4Bz/download
wget -O $HOME/Desktop/presentatie.odp https://owncloud.fambaron.nl/s/TQqsDg594qeReY8/download

# install Visual Studio Code
# FIXME Find reliable download link
which code > /dev/null || (wget -O /tmp/vc.deb https://go.microsoft.com/fwlink/?LinkID=760868 && sudo apt install -y /tmp/vc.deb)

echo '{ "insecure-registries" : ["'cursusregistry':5000"] }' | sudo tee /etc/docker/daemon.json > /dev/null
docker ps -q > /dev/null        # ensure docker deamon is started
sudo systemctl reload docker

if [[ ! -d "$HOME/dockercourse" ]]; then
	(cd $HOME && git clone https://github.com/bertbaron/dockercourse.git)
fi

(cd $HOME/dockercourse && git pull) || echo "PULL FAILED!"

echo "Installation complete"
