#!/bin/bash
#
# Script to install stuff locally on course pc's
#
# To execute, run:
#
# wget -O localinstall https://raw.githubusercontent.com/bertbaron/dockercourse-setup/master/localinstall && bash ./localinstall

set -eu -o pipefail


last_update=$(stat -c %Y /var/lib/apt/periodic/update-success-stamp)
now=$(date +%s)
if [ $((now - last_update)) -gt 3600 ]; then
  sudo apt-get update
fi

install() {
	cmd="$1"
	package="$2"
	which "$cmd" > /dev/null || sudo apt-get install -y "$package"
}

addToDockerGroup() {
  sudo usermod -a -G docker $USER
  echo "User added to docker group, new login required"
  exit 1
}

groups | grep docker || addToDockerGroup

# TODO install docker
install docker-compose docker-compose
install git git
install vim vim

# install Visual Studio Code
# FIXME Find reliable download link
#which code > /dev/null || wget -O /tmp/vc.deb https://go.microsoft.com/fwlink/?LinkID=760868 && sudo apt install /tmp/vc.deb

echo '{ "insecure-registries" : ["'cursusregistry':5000"] }' | sudo tee /etc/docker/daemon.json
sudo systemctl reload docker

if [[ ! -d "$HOME/dockercourse" ]]; then
	(cd $HOME && git clone https://github.com/bertbaron/dockercourse.git)
fi

(cd $HOME/dockercourse && git pull) || echo "PULL FAILED!"
