#!/bin/bash

which docker >/dev/null || sudo apt-get install -y docker.io
which nmap >/dev/null || sudo apt-get -y nmap

sudo usermod -a -G docker ubuntu
groups | grep -qw docker || (echo "You may need to login again"; exit 1)

echo "done"