---
- name: Update APT package cache
  apt:
    update_cache: yes
    cache_valid_time: 3600
  register: apt_cache_result

- name: Install aptitude (requirement for apt module)
  package:
    name: aptitude
    state: latest

- debug:
    var: apt_cache_result
    verbosity: 2

- name: Upgrade APT to the lastest packages
  apt:
    upgrade: safe
  when: apt_cache_result|changed